package tilejson

var contourLayerFields = map[string]string{"elevation": "Corrected elevation of contour. (Includes elevationOffset)", "dem_elevation": "DEM elevation of contour."}

var locationLayerFields = map[string]string{
	"name":    "Corresponds to value in map config.",
	"radiusA": "Corresponds to value in map config.",
	"radiusB": "Corresponds to value in map config.",
	"angle":   "Corresponds to value in map config.",
}

var vectorLayerFields = map[string]map[string]string{
	"contours/01":                   contourLayerFields,
	"contours/05":                   contourLayerFields,
	"contours/10":                   contourLayerFields,
	"contours/100":                  contourLayerFields,
	"contours/50":                   contourLayerFields,
	"house":                         {"color": "House color as a CSS rgb() string.", "height": "Height of the building in meters"},
	"mount":                         {"elevation": "Elevation as float", "text": "Rounded elevation as a string"},
	"locations/respawn_unknown":     locationLayerFields,
	"locations/respawn_inf":         locationLayerFields,
	"locations/respawn_motor":       locationLayerFields,
	"locations/respawn_armor":       locationLayerFields,
	"locations/respawn_air":         locationLayerFields,
	"locations/respawn_plane":       locationLayerFields,
	"locations/respawn_naval":       locationLayerFields,
	"locations/respawn_para":        locationLayerFields,
	"locations/group_0":             locationLayerFields,
	"locations/group_1":             locationLayerFields,
	"locations/group_2":             locationLayerFields,
	"locations/group_3":             locationLayerFields,
	"locations/group_4":             locationLayerFields,
	"locations/group_5":             locationLayerFields,
	"locations/group_6":             locationLayerFields,
	"locations/group_7":             locationLayerFields,
	"locations/group_8":             locationLayerFields,
	"locations/group_9":             locationLayerFields,
	"locations/group_10":            locationLayerFields,
	"locations/group_11":            locationLayerFields,
	"locations/b_unknown":           locationLayerFields,
	"locations/o_unknown":           locationLayerFields,
	"locations/n_unknown":           locationLayerFields,
	"locations/b_inf":               locationLayerFields,
	"locations/o_inf":               locationLayerFields,
	"locations/n_inf":               locationLayerFields,
	"locations/b_motor_inf":         locationLayerFields,
	"locations/o_motor_inf":         locationLayerFields,
	"locations/n_motor_inf":         locationLayerFields,
	"locations/b_mech_inf":          locationLayerFields,
	"locations/o_mech_inf":          locationLayerFields,
	"locations/n_mech_inf":          locationLayerFields,
	"locations/b_armor":             locationLayerFields,
	"locations/o_armor":             locationLayerFields,
	"locations/n_armor":             locationLayerFields,
	"locations/b_recon":             locationLayerFields,
	"locations/o_recon":             locationLayerFields,
	"locations/n_recon":             locationLayerFields,
	"locations/b_air":               locationLayerFields,
	"locations/o_air":               locationLayerFields,
	"locations/n_air":               locationLayerFields,
	"locations/b_plane":             locationLayerFields,
	"locations/o_plane":             locationLayerFields,
	"locations/n_plane":             locationLayerFields,
	"locations/b_uav":               locationLayerFields,
	"locations/o_uav":               locationLayerFields,
	"locations/n_uav":               locationLayerFields,
	"locations/b_naval":             locationLayerFields,
	"locations/o_naval":             locationLayerFields,
	"locations/n_naval":             locationLayerFields,
	"locations/b_med":               locationLayerFields,
	"locations/o_med":               locationLayerFields,
	"locations/n_med":               locationLayerFields,
	"locations/b_art":               locationLayerFields,
	"locations/o_art":               locationLayerFields,
	"locations/n_art":               locationLayerFields,
	"locations/b_mortar":            locationLayerFields,
	"locations/o_mortar":            locationLayerFields,
	"locations/n_mortar":            locationLayerFields,
	"locations/b_hq":                locationLayerFields,
	"locations/o_hq":                locationLayerFields,
	"locations/n_hq":                locationLayerFields,
	"locations/b_support":           locationLayerFields,
	"locations/o_support":           locationLayerFields,
	"locations/n_support":           locationLayerFields,
	"locations/b_maint":             locationLayerFields,
	"locations/o_maint":             locationLayerFields,
	"locations/n_maint":             locationLayerFields,
	"locations/b_service":           locationLayerFields,
	"locations/o_service":           locationLayerFields,
	"locations/n_service":           locationLayerFields,
	"locations/b_installation":      locationLayerFields,
	"locations/o_installation":      locationLayerFields,
	"locations/n_installation":      locationLayerFields,
	"locations/u_installation":      locationLayerFields,
	"locations/b_antiair":           locationLayerFields,
	"locations/o_antiair":           locationLayerFields,
	"locations/n_antiair":           locationLayerFields,
	"locations/c_unknown":           locationLayerFields,
	"locations/c_car":               locationLayerFields,
	"locations/c_ship":              locationLayerFields,
	"locations/c_air":               locationLayerFields,
	"locations/c_plane":             locationLayerFields,
	"locations/flag":                locationLayerFields,
	"locations/rockarea":            locationLayerFields,
	"locations/viewpoint":           locationLayerFields,
	"locations/hill":                locationLayerFields,
	"locations/bordercrossing":      locationLayerFields,
	"locations/vegetationbroadleaf": locationLayerFields,
	"locations/vegetationfir":       locationLayerFields,
	"locations/vegetationpalm":      locationLayerFields,
	"locations/vegetationvineyard":  locationLayerFields,
	"locations/handdrawncamp":       locationLayerFields,
	"locations/name":                locationLayerFields,
	"locations/faketown":            locationLayerFields,
	"locations/strategic":           locationLayerFields,
	"locations/strongpointarea":     locationLayerFields,
	"locations/flatarea":            locationLayerFields,
	"locations/flatareacity":        locationLayerFields,
	"locations/flatareacitysmall":   locationLayerFields,
	"locations/citycenter":          locationLayerFields,
	"locations/civildefense":        locationLayerFields,
	"locations/culturalproperty":    locationLayerFields,
	"locations/dangerousforces":     locationLayerFields,
	"locations/safetyzone":          locationLayerFields,
	"locations/airport":             locationLayerFields,
	"locations/namemarine":          locationLayerFields,
	"locations/namelocal":           locationLayerFields,
	"locations/namevillage":         locationLayerFields,
	"locations/namecity":            locationLayerFields,
	"locations/namecitycapital":     locationLayerFields,
	"locations/mount":               locationLayerFields,
	"locations/invisible":           locationLayerFields,
	"locations/historicalsite":      locationLayerFields,
	"locations/area":                locationLayerFields,
}
